export const sampleReceiptColumns = [
	{ title: "Sample Receipt ID", field: "samplereceiptid" },
	{ title: "Study Name", field: "studyname" },
	{ title: "Subject", field: "subject" },
	{ title: "Visit Name", field: "visitname" },
	{ title: "Visit Date", field: "visitdate" },
	{ title: "Age at Visit", field: "ageatvisit" },
	{ title: "Sample Collection Date", field: "samplecollectiondate" },
	{ title: "Time of Blood Time", field: "blooddrawtime" },
	{ title: "Sample Receipt Date", field: "samplereceiptdate" },
	{ title: "Time of Sample Receipt", field: "samplereceipttime" },
	{ title: "Hematology Sample", field: "hematologysample" },
	{ title: "Chemistry Sample", field: "chemistrysample" },
	{ title: "Humoral Sample", field: "humoralsample" },
	{ title: "Cellular Sample", field: "cellularsample" },
	{ title: "Comments", field: "comments" },
	{ title: "Date Created", field: "createdAt" },
	{ title: "Added By", field: "tbl_user.firstName" },
];

export const humoralSampleColumns = [
	{ title: "Humoral Sample Storage ID", field: "humoralsamplestorageid" },
	{ title: "Box ID", field: "boxid" },
	{ title: "Aliquot ID", field: "aliquotid" },
	{ title: "Subject", field: "subject" },
	{ title: "Visit Name", field: "visitname" },
	{ title: "Sample Type", field: "sampletype" },
	{ title: "Aliqout", field: "aliquot" },
	{ title: "AID", field: "aid" },
	{ title: "Room Location", field: "roomlocation" },
	{ title: "Freezer Number", field: "freezernumber" },
	{ title: "Box Number", field: "boxnumber" },
	{ title: "Column Number", field: "columnnumber" },
	{ title: "Row Number", field: "rownumber" },
	{ title: "Shipped", field: "shipped" },
	{ title: "Shipped Date", field: "shippeddate" },
	{ title: "Comments", field: "comments" },
	{ title: "Date Created", field: "createdAt" },
	{ title: "Added By", field: "tbl_user.firstName" },
];

export const PBMCSample = [
	{ title: "PBMC Sample ID", field: "pbmcsampletid" },
	{ title: "Subject", field: "subject" },
	{ title: "Visit Name", field: "visitname" },
	{ title: "AID", field: "aid" },
	{ title: "Aliquot", field: "aliquot" },
	{ title: "Aliquot ID", field: "aliquotid" },
	{ title: "Box ID", field: "boxid" },
	{ title: "Box Number", field: "boxnumber" },
	{ title: "Column Number", field: "columnnumber" },
	{ title: "Freezer Number", field: "freezernumber" },
	{ title: "Room Location", field: "roomlocation" },
	{ title: "Sample Type", field: "sampletype" },
	{ title: "Shipped", field: "shipped" },
	{ title: "Shipped Date", field: "shippeddate" },
	{ title: "Comments", field: "comments" },
	{ title: "Date Created", field: "createdAt" },
	{ title: "Added By", field: "tbl_user.firstName" },
];
